async function getLLMResponse(question,solution,errorMessage) {

    const cleanCode = solution.map(line => line.trim()).filter(line => line !== '');
    const fullCode = cleanCode.join('\n');
    console.log('Received content - ',question,fullCode )
    try {
      const response = await fetch('https://survey.dfki.de/quantumtutorllm', {
      method: 'POST',
      headers: {
              'Content-Type': 'application/json',
              'Authorization': 'mysecret123test'
      },
      body: JSON.stringify({
        "body":{
        "question": question,
        "fullCode": fullCode
        }
      })
      });
      console.log('Server response :-',response)
      if (!response.ok) {
        throw new Error('Error communicating with server:- ',response.status);
      }
      else{
        const data = await response.json();
        return data.message;
      }

    } catch (error) {
      console.error("Error communicating with server:", error);
    }
  }

/*
async function getLLMResponse(question,solution,errorMessage) {
  console.log('Get LLM Response called',errorMessage)
    try {

      let llmPromt = `Based on the information given, give the struggling student a hint 
      that helps him answer the following question, without giving away the answer. 
      Be more specific and formulate your tip as if you were talking to a novice. 
      Original error message which is generated by a coding webpage is also provided, use it to better guide the student.
      Ignore any question passed in the solution.
      Be as concise as possible and give a hint in not more than 7 words. The format of the output should be:-
       Hint - Your response`;
      llmPromt = llmPromt + 'Question:- ' + question
      llmPromt = llmPromt + 'Students solution:- ' + solution
      llmPromt = llmPromt + 'Original error message:- ' + errorMessage
  
          const response = await fetch('https://api.openai.com/v1/chat/completions', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': 'API KEY '
            },
            body: JSON.stringify({
              model: 'gpt-4o-mini',
              messages: [
                { role: 'system', content: 'You are a passionate and patient quantum-physics teacher checking coding exercise answers of students. ' },
                { role: 'user', content: llmPromt }
              ],
              max_tokens: 150
            })
          });
          if (!response.ok) {
            throw new Error('Error communicating with the LLM with response:- ',response.status);
          }
          const result = await response.json();
          console.log('Got result :- ',result.choices[0].message.content)
          return result.choices[0].message.content;

    } catch (error) {
      console.error("Error communicating with LLM:", error);
    }
  }
    */